### ISSUE TITLE
Error in GET['cmd'] lines

### ISSUE THREAD

**Issue by sbrooke** [mmdoogie/roku-imgserver-screensaver-server#1]
I'm getting: 

`Undefined array key "cmd" in /var/www/html/imgserver.php on line 9`

Every time I try to run it. Tried it with one of the generic public URLs and the behavior didn't change, so it's not a Grafana specific thing. 

PHP Version 8.1.2-1ubuntu2.11
Ubuntu 22.04

**Comment by mmdoogie** [comment]
You don’t have to run it directly, it would be accessed through a HTTP request like imgserver.php?cmd=descs should give the array of image descriptions. I probably need to fix that error check but it shouldn’t come up in normal use.

**Comment by sbrooke** [comment]
It's not working for me and that's the only log entry I see, so I thought it might be crashing on that. To be clear, if I try to access it from the Roku app or directly at the imgserver.php url through a browser it generates this log entry. I'm not only running it from the CLI, although when I do I get the same error message.

If I comment out the line 9 section it errors on the same thing on line 14.

I didn't state this in the previous comment, but it's not working. Blank screen in both Roku and a browser access to the imgserver.php url.

**Comment by sbrooke** [comment]
Ok, so running the following generated a result:

`http://192.168.1.18/imgserver/imgserver.php?cmd=descs`

So, maybe I should ignore this error in the logs and focus on why the Roku channel isn't displaying anything?

**Comment by mmdoogie** [comment]
Ok if that looks like the descriptions you configured, then try cmd=img&num=0 to try to load the first image and see if you get a different issue there.

**Comment by sbrooke** [comment]
Looks like I'm getting permissions errors for writing the file now, so that's a good sign. I'll try to fix that...

**Comment by sbrooke** [comment]
Yep, fixing permissions seems to have fixed the issue. Now for a complex Grafana dashboard...

**Comment by sbrooke** [comment]
This issue appears to be resolved. I'm having a problem with the grafana dashboard formatting, but I can open a separate issue if I can't sort that out. Thanks for the quick response!
